### ISSUE TITLE
apertium-eo-fr fails to build

### ISSUE THREAD

**Issue by kartikm** [apertium/apertium-eo-fr#3]
apertium-eo-fr seems fails to build in Debian. Looks like it requires `apertium-preprocess-transfer-bytecode-j` which is not packaged or apertium-eo-fr needs update to new tool.

Other details:
* Version: 0.9.0~r57551
* OS: Debian GNU/Linux Unstable

Log:
...
Warning (31015): Paths to rule 319 blocked by rule 281.
Warning (31015): Paths to rule 319 blocked by rule 281.
Warning (31015): Paths to rule 319 blocked by rule 281.
Warning (31015): Paths to rule 319 blocked by rule 281.
Warning (31015): Paths to rule 319 blocked by rule 281.
/bin/bash: line 0: command: apertium-preprocess-transfer-bytecode-j: not found
NOTE: lttoolbox-java (used for bytecode accelerated transfer) is missing
     but that's OK

make[2]: Leaving directory '/build/apertium-eo-fr-0.9.0~r57551'
make[1]: *** [Makefile:630: install-am] Error 2
make[1]: Leaving directory '/build/apertium-eo-fr-0.9.0~r57551'
dh_auto_install: make -j4 install
DESTDIR=/build/apertium-eo-fr-0.9.0\~r57551/debian/apertium-eo-fr
AM_UPDATE_INFO_DIR=no returned exit code 2
make: *** [debian/rules:9: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess
returned exit status 2

**Comment by TinoDidriksen** [comment]
Works for me. Need more of the log to see what's actually wrong, because the Java message is just a warning - it also happens in the working build.

**Comment by kartikm** [comment]
Looks like it fails with dh 11 :/

**Comment by kartikm** [comment]
Build file attached.
[apertium-eo-fr_0.9.0~r57551-2_amd64.build.txt](https://github.com/apertium/apertium-eo-fr/files/2189398/apertium-eo-fr_0.9.0.r57551-2_amd64.build.txt)

**Comment by TinoDidriksen** [comment]
The actual error is:
````
test -d /build/apertium-eo-fr-0.9.0~r57551/debian/apertium-eo-fr/usr/share/apertium/modes/ || mkdir /build/apertium-eo-fr-0.9.0~r57551/debian/apertium-eo-fr/usr/share/apertium/modes/
mkdir: cannot create directory ‘/build/apertium-eo-fr-0.9.0~r57551/debian/apertium-eo-fr/usr/share/apertium/modes/’: No such file or directory
````

My build performs ` /bin/mkdir -p '/build/apertium-eo-fr-0.9.0+g191~b7f5a3ea/debian/apertium-eo-fr/usr/share/apertium/apertium-eo-fr/'` which allows for the later mkdir, but your build does not. Maybe a parallel install issue?

**Comment by kartikm** [comment]
Yes. parallel build issue `--no-parallel` fixed that. But, should it be fix upstream?

**Comment by TinoDidriksen** [comment]
Fixed globally in https://github.com/apertium/apertium/commit/2c0e7e09b0ae5d158410773285ee3ae4f55cfe92 and locally in https://github.com/apertium/apertium-eo-fr/commit/f7d25656a7e0661db028229d20499367188d4dbc
